add history to todo

diff --git a/home/scripts/.local/bin/todo b/home/scripts/.local/bin/todo
--- a/home/scripts/.local/bin/todo
+++ b/home/scripts/.local/bin/todo
@@ -2,7 +2,10 @@
 
 export SHELL=$(which fish)
 
-fzf="fzf"
+if ! command -v $git &> /dev/null; then
+  >&2 echo "projects: git command could not be found"
+  exit
+fi
 
 if ! command -v $EDITOR &> /dev/null; then
   >&2 echo "todo: $EDITOR editor set by \$EDITOR env variable could not be found"
@@ -10,7 +13,18 @@ if ! command -v $EDITOR &> /dev/null; then
 fi
 
 todo=${TODO_DIR:-"$HOME/.todo"}
-[ ! -d "$todo" ] && mkdir -p "$todo/archive"
+archive="$todo/archive"
+if [ ! -d "$todo" ]; then
+  git init $todo
+  mkdir -p $archive
+fi
+
+function git_history() {
+  message=$1
+  git -C $todo add $todo > /dev/null
+  id=$(git -C $todo diff --cached --name-only)
+  git -C $todo commit -m "$id $message" > /dev/null
+}
 
 case "$1" in
   ar*)
@@ -18,8 +32,9 @@ case "$1" in
     if [ -z "$target" ]; then
       >&2 echo "todo: usage: todo archive <task-id>"
     else
-      mv -i $todo/$target* $todo/archive
+      mv -i $todo/$target* $archive
     fi
+    git_history "archived"
     ;;
 
   l*)
@@ -42,6 +57,15 @@ case "$1" in
     done
     ;;
 
+  h*)
+    id=$2
+    if [ -z "$id"]; then
+      git -C $todo log --format="%ci : %s"
+    else
+      git -C $todo log -p --format="%n%ci : %s" -- $id
+    fi
+    ;;
+
   a*)
     id=$(date +%s | sha1sum - | cut -d ' ' -f 1)
     shift
@@ -52,6 +76,7 @@ case "$1" in
       echo "$summary" > $todo/$id
     fi
     if [ -s $todo/$id ]; then
+      git_history "added"
       echo $id
     else
       >&2 echo "todo: nothing to add"
@@ -64,6 +89,7 @@ case "$1" in
       >&2 echo "todo: usage: todo remove <task-id>"
     else
       rm -i $todo/$target
+      git_history "removed"
     fi
     ;;
 
@@ -73,6 +99,7 @@ case "$1" in
       >&2 echo "todo: usage: todo edit <task-id>"
     else
       $EDITOR $todo/$target*
+      git_history "edited"
     fi
     ;;
 
@@ -92,10 +119,11 @@ case "$1" in
       >&2 echo "todo: usage: todo tag <task-id> <tag>"
     else
       echo "$tag" >> $todo/$target*
+      git_history "tagged"
     fi
     ;;
 
   *)
-    >&2 echo "usage: todo [list|add|edit|show|remove|archive|tag|help]"
+    >&2 echo "usage: todo [list|add|edit|show|remove|archive|tag|history|help]"
     ;;
 esac
